service: python-web-crawler

frameworkVersion: ">=2.24.0"

useDotenv: true

package:
  patterns:
    - '!node_modules/**'

provider:
  name: aws
  runtime: python3.10
  profile: ${env:AWS_PROFILE, 'default'}
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}
  iam:
    role: ${env:AWS_IAM_ROLE, 'lambda'}
  apiGateway:
    shouldStartNameWithService: true

functions:
  crawler:
    handler: handler.crawl
    events:
      - http:
          path: /crawl
          method: get
plugins:
  - serverless-offline
  - serverless-python-requirements
