service: python-web-crawler

frameworkVersion: ">=2.24.0"

provider:
  name: aws
  runtime: python3.10
  profile: ${env:AWS_PROFILE, ''}
  stage: ${opt:stage, 'production'}
  region: ${opt:region, 'eu-west-1'}
  apiGateway:
    shouldStartNameWithService: true

functions:
  hello:
    handler: handler.crawl
    events:
      - http:
          path: /crawl
          method: get
plugins:
  - serverless-offline
  - serverless-python-requirements
